import { z } from "zod";

export const CATEGORIES = [
  "Art Show",
  "Awards",
  "Auction",
  "Block Party",
  "Barbecue",
  "Boot Camp",
  "Carnival",
  "Ceremony",
  "Concert",
  "Conference",
  "Contest",
  "Cultural",
  "Dinner",
  "Fairs",
  "Film",
  "Exhibition",
  "Dance",
  "Cosplay",
  "Fundraiser",
  "Graduation",
  "Holiday",
  "Food",
  "Hackathon",
  "Homecoming",
  "Lecture",
  "Meeting",
  "Presentations",
  "Picnic",
  "Parade",
  "Private",
  "Protest",
  "Reception",
  "Reunion",
  "Ritual",
  "Seminar",
  "Sports",
  "Recital",
  "Product Launch",
  "Roadshow",
  "Showcase",
  "Talk",
  "Tradition",
  "Wedding",
  "Workshop",
  "Video",
  "Trade",
  "Talent Show",
] as const;

const CategoryEnum = z.enum(CATEGORIES);

export type TCategory = z.infer<typeof CategoryEnum>;
